name: Google Home Bridge
slug: googlehome_bridge
version: "1.0.0"
description: "Bridge for Google Home / OAuth Smart Home fulfillment."
url: "https://github.com/youruser/googlehome_bridge"
startup: services
boot: auto
arch:
  - amd64
  - arm64
  - armv7
map:
  - config:rw
  - share:rw
ports:
  5000/tcp: 5000
webui: "http://[HOST]:[PORT:5000]/admin"
watchdog: "http://[HOST]:[PORT:5000]/health"
ingress: false
panel_icon: mdi:google-assistant
environment:
  PORT: 5000
  DEBUG: "false"
  CLIENT_ID: "CHANGE_ME"
  CLIENT_SECRET: "CHANGE_ME"
  HA_URL: "http://supervisor/core"
  HA_TOKEN: "USE_LONG_LIVED_OR_SUPERVISOR_TOKEN"
schema:
  client_id: str?
  client_secret: str?
  debug: bool?
  expose_sensors: bool?
  expose_temperature: bool?
  expose_humidity: bool?
  expose_power: bool?
  expose_generic: bool?
options:
  client_id: "CHANGE_ME"
  client_secret: "CHANGE_ME"
  debug: false
  expose_sensors: true
  expose_temperature: true
  expose_humidity: true
  expose_power: false
  expose_generic: false
