name: Google Home Bridge
slug: googlehome_bridge
version: "1.0.2"
description: "Bridge for Google Home / OAuth Smart Home fulfillment."
url: "https://github.com/Codarax/googlehome_bridge"
startup: services
boot: auto
arch:
  - amd64
  - arm64
  - armv7
map:
  - config:rw
  - share:rw
ports:
  5000/tcp: 5000
webui: "http://[HOST]:[PORT:5000]/admin"
watchdog: "http://[HOST]:[PORT:5000]/health"
ingress: false
panel_icon: mdi:google-assistant
schema:
  client_id: str?
  client_secret: str?
  ha_url: str?
  ha_token: str?
  debug: bool?
  expose_sensors: bool?
  expose_temperature: bool?
  expose_humidity: bool?
  expose_power: bool?
  expose_generic: bool?
options:
  client_id: "CHANGE_ME"
  client_secret: "CHANGE_ME"
  ha_url: "http://supervisor/core"
  ha_token: ""
  debug: false
  expose_sensors: true
  expose_temperature: true
  expose_humidity: true
  expose_power: false
  expose_generic: false
