name: Build & Publish Google Home Bridge Addon

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9+]'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive lowercase owner
        id: meta
        run: |
          OWNER=${GITHUB_REPOSITORY%/*}
          echo "owner_lc=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: version
        run: |
          RAW_TAG=${GITHUB_REF##*/}
          CLEAN_TAG=${RAW_TAG#v}
          echo "raw_tag=${RAW_TAG}" >> $GITHUB_OUTPUT
          echo "clean_tag=${CLEAN_TAG}" >> $GITHUB_OUTPUT
      - name: Build & Push Multi-Arch Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: googlehome_bridge/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/googlehome_bridge:${{ steps.version.outputs.raw_tag }}
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/googlehome_bridge:${{ steps.version.outputs.clean_tag }}
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/googlehome_bridge:latest
          build-args: |
            BUILD_VERSION=${{ steps.version.outputs.clean_tag }}
